const SECTION_META={1:{title:'Crime report form',range:'Questions 1–10',file:'media/section1.m4a'},2:{title:'Induction talk for new apprentices',range:'Questions 11–20',file:'media/section2.m4a'},3:{title:'Cities built by the sea',range:'Questions 21–30',file:'media/section3.m4a'},4:{title:'Marine renewable energy',range:'Questions 31–40',file:'media/section4.m4a'}};
const OPTIONS={
 advice:{A:'get to know colleagues',B:'learn from any mistakes',C:'ask lots of questions',D:'react positively to feedback',E:'enjoy new challenges'},
 mentor:{A:'confidence-building',B:'making career plans',C:'completing difficult tasks',D:'making a weekly timetable',E:'reviewing progress'},
 policy:{A:'It is encouraged.',B:'There are some restrictions.',C:'It is against the rules.'},
 q21:{A:"contain nearly half the world's population.",B:"include most of the world's largest cities.",C:'are growing twice as fast as other cities.'},
 q22:{A:'may bring pollution to the cities.',B:'may reduce the land available for agriculture.',C:'may mean the countryside is spoiled by industry.'},
 q23:{A:'There were not enough of them.',B:'They were made of unsuitable materials.',C:'They did not allow for the effects of climate change.'},
 q24:{A:'take measures to restore ecosystems',B:'pay for a new flood prevention system',C:'stop disposing of waste materials into the ocean'},
 q25:{A:'greater coordination of activities',B:'more sharing of information',C:'agreement on shared policies'},
 decisions:{A:'use visuals',B:'keep it short',C:'involve other students',D:'check the information is accurate',E:'provide a handout',F:'focus on one example',G:'do online research'}
};
let questions=[];let mode='exam';let currentSection=1;let currentQuestion=1;let answers={};let flags={};let results=null;let timeLeft=2400;let timerId=null;let examAudioUsed={};let saveTimer=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const audio=$('#audio');

async function init(){questions=window.QUESTIONS||[];if(!questions.length)throw new Error('Không tìm thấy dữ liệu câu hỏi.');restore();bind();renderNav();renderPalette();updateSection(1,false);updateProgress();}
function bind(){
 $$('.mode-card').forEach(b=>b.onclick=()=>{$$('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');mode=b.dataset.mode});
 $('#startBtn').onclick=startApp; $('#submitTop').onclick=submitTest; $('#clearBtn').onclick=resetTest; $('#retryBtn').onclick=()=>{closeAll();resetTest(true)};
 $('#closeResult').onclick=()=>$('#resultModal').classList.add('hidden'); $('#reviewBtn').onclick=openReview; $('#closeReview').onclick=()=>$('#reviewModal').classList.add('hidden');
 $('#wrongOnly').onchange=renderReview; $('#reviewWrongBtn').onclick=()=>{if(!results){toast('Hãy nộp bài để mở kho lỗi sai.');return} openReview(true)};
 $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('ielts-theme',document.body.classList.contains('dark')?'dark':'light')};
 if(localStorage.getItem('ielts-theme')==='dark')document.body.classList.add('dark');
 $('#playBtn').onclick=toggleAudio; $('#back10').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10); $('#forward10').onclick=()=>audio.currentTime=Math.min(audio.duration||0,audio.currentTime+10);
 $('#seek').oninput=e=>{if(mode==='practice'&&audio.duration)audio.currentTime=audio.duration*(e.target.value/1000)};
 $('#speed').onchange=e=>audio.playbackRate=+e.target.value;
 audio.ontimeupdate=updateAudioUI; audio.onloadedmetadata=updateAudioUI; audio.onplay=()=>$('#playBtn').textContent='❚❚'; audio.onpause=()=>$('#playBtn').textContent='▶'; audio.onended=()=>{$('#playBtn').textContent='▶';examAudioUsed[currentSection]=true;persist()};
 $('#prevSection').onclick=()=>updateSection(Math.max(1,currentSection-1)); $('#nextSection').onclick=()=>currentSection===4?submitTest():updateSection(currentSection+1);
 $('#flagCurrent').onclick=()=>toggleFlag(currentQuestion); window.addEventListener('beforeunload',persist);
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')submitTest();if(e.key===' '&&['INPUT','SELECT','TEXTAREA'].indexOf(document.activeElement.tagName)<0){e.preventDefault();toggleAudio()}});
}
function startApp(){const name=$('#candidateName').value.trim()||'Học viên';localStorage.setItem('ielts-name',name);$('#candidateDisplay').textContent=name;$('#avatar').textContent=name.split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();$('#welcome').classList.add('hidden');$('#app').classList.remove('hidden');$('#modeLabel').textContent=mode==='exam'?'Chế độ thi thật':'Chế độ luyện tập';configureMode();if(results)renderResult();if(mode==='exam'&&!results)startTimer();toast(results?'Đã khôi phục kết quả lần làm trước.':(mode==='exam'?'Đã bắt đầu bài thi 40 phút.':'Đã bật chế độ luyện tập.'));}
function configureMode(){const practice=mode==='practice';$('#back10').disabled=!practice;$('#forward10').disabled=!practice;$('#seek').disabled=!practice;$('#speed').disabled=!practice;$('#audioRule').textContent=practice?'Có thể tua và đổi tốc độ':'Audio chỉ phát 1 lần';$('#timer').classList.toggle('hidden',practice);}
function startTimer(){clearInterval(timerId);renderTimer();timerId=setInterval(()=>{timeLeft--;renderTimer();if(timeLeft<=0){clearInterval(timerId);toast('Hết giờ — bài đã được nộp tự động.');submitTest(true)}persist()},1000)}
function renderTimer(){let m=Math.floor(timeLeft/60),s=timeLeft%60;$('#timer b').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('warning',timeLeft<=300&&timeLeft>60);$('#timer').classList.toggle('danger',timeLeft<=60)}
function renderNav(){const nav=$('#sectionNav');nav.innerHTML=Object.entries(SECTION_META).map(([n,m])=>`<button class="section-btn" data-section="${n}"><span class="section-num">${n}</span><div><b>Section ${n}</b><small>${m.range}</small></div><span class="section-score" id="secScore${n}"></span></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>updateSection(+b.dataset.section))}
function renderPalette(){const p=$('#palette');p.innerHTML=questions.map(q=>`<button class="qdot" data-q="${q.id}">${q.id}</button>`).join('');p.querySelectorAll('button').forEach(b=>b.onclick=()=>goQuestion(+b.dataset.q));updatePalette()}
function updatePalette(){$$('.qdot').forEach(b=>{const id=+b.dataset.q;b.classList.toggle('answered',isAnswered(id));b.classList.toggle('flagged',!!flags[id]);b.classList.toggle('current',id===currentQuestion)});}
function updateSection(n,scroll=true){pauseAudio();currentSection=n;const meta=SECTION_META[n];audio.src=meta.file;audio.load();$('#audioSection').textContent='S'+n;$('#audioTitle').textContent=meta.title;$('#sectionLabel').textContent='Section '+n;$$('.section-btn').forEach(b=>b.classList.toggle('active',+b.dataset.section===n));renderPaper();updatePalette();$('#prevSection').disabled=n===1;$('#nextSection').textContent=n===4?'Nộp bài ✓':'Section tiếp →';if(scroll)window.scrollTo({top:0,behavior:'smooth'});persist()}
function renderPaper(){const q=questions.filter(x=>x.section===currentSection);let body='';if(currentSection===1)body=renderSection1(q);if(currentSection===2)body=renderSection2(q);if(currentSection===3)body=renderSection3(q);if(currentSection===4)body=renderSection4(q);$('#testPaper').innerHTML=paperHeader(currentSection)+body;bindInputs();}
function paperHeader(n){const m=SECTION_META[n];return `<header class="paper-header"><div><span class="eyebrow">IELTS LISTENING PRACTICE</span><h1>SECTION ${n}</h1><p>${m.title}</p></div><span class="section-pill">${m.range}</span></header>`}
function inputText(q,placeholder='Type your answer'){return `<input data-id="${q.id}" value="${esc(answers[q.id]||'')}" placeholder="${placeholder}" autocomplete="off" spellcheck="false">`}
function flagButton(id){return `<button class="flag-btn ${flags[id]?'on':''}" data-flag="${id}" title="Đánh dấu">${flags[id]?'★':'☆'}</button>`}
function renderSection1(q){const by=id=>q.find(x=>x.id===id);return `<div class="instruction"><b>Complete the form below.</b><br>Write <b>ONE WORD AND/OR A NUMBER</b> for each answer.</div><div class="form-sheet"><div class="form-title">CRIME REPORT FORM</div><div class="form-section"><div class="form-line"><b>Type of crime</b><span>theft</span></div></div><div class="form-section"><h3>Personal information</h3><div class="form-line"><span>Name</span><b>Louise Taylor</b></div><div class="form-line"><span><i class="inline-num">1</i>Nationality</span>${inputText(by(1))}</div><div class="form-line"><span>Date of birth</span><b>14 December 1977</b></div><div class="form-line"><span>Occupation</span><b>interior designer</b></div><div class="form-line"><span><i class="inline-num">2</i>Reason for visit</span><span>business — to buy antique ${inputText(by(2),'answer')}</span></div><div class="form-line"><span>Length of stay</span><b>two months</b></div><div class="form-line"><span><i class="inline-num">3</i>Current address</span><span>${inputText(by(3),'answer')} Apartments (No 15)</span></div></div><div class="form-section"><h3>Details of theft</h3><div class="form-line"><span><i class="inline-num">4</i>Wallet containing approximately £</span>${inputText(by(4),'amount')}</div><div class="form-line"><span><i class="inline-num">5</i>Second item stolen</span>${inputText(by(5))}</div><div class="form-line"><span><i class="inline-num">6</i>Date of theft</span>${inputText(by(6),'date')}</div></div><div class="form-section"><h3>Possible time, place and suspect</h3><div class="form-line"><span><i class="inline-num">7</i>Outside the ___ at about 4 pm</span>${inputText(by(7))}</div><div class="form-line"><span><i class="inline-num">8</i>Boys asked for the ___</span>${inputText(by(8))}</div><div class="form-line"><span><i class="inline-num">9</i>Slim build with ___ hair</span>${inputText(by(9))}</div><div class="form-line"><span><i class="inline-num">10</i>Crime reference number</span>${inputText(by(10),'number')}</div></div></div>`}
function renderOptions(group,ids,opts){const selected=ids.map(id=>answers[id]).filter(Boolean);return `<div class="option-list">${Object.entries(opts).map(([l,t])=>`<label class="option"><input type="checkbox" data-pair="${group}" data-ids="${ids.join(',')}" value="${l}" ${selected.includes(l)?'checked':''}><span class="letter">${l}</span><span>${t}</span></label>`).join('')}</div>`}
function renderSection2(q){const policies=q.filter(x=>x.id>=15);return `<div class="instruction">Listen to a manager giving a welcome talk to new apprentices.</div><div class="group-box" id="q11"><h3>Questions 11 and 12</h3><p>Choose <b>TWO</b> pieces of advice for the first week.</p>${renderOptions('advice',[11,12],OPTIONS.advice)}</div><div class="group-box" id="q13"><h3>Questions 13 and 14</h3><p>Choose <b>TWO</b> things mentors can help with.</p>${renderOptions('mentor',[13,14],OPTIONS.mentor)}</div><div class="group-box"><h3>Questions 15–20 — Company policy</h3><p>Write the correct letter A, B or C.</p><div class="policy-key">${Object.entries(OPTIONS.policy).map(([l,t])=>`<div class="key-row"><b>${l}</b><span>${t}</span></div>`).join('')}</div>${policies.map(x=>questionSelect(x,OPTIONS.policy)).join('')}</div>`}
function questionSelect(q,opts){return `<div class="question-card" id="q${q.id}"><div class="qrow"><span class="qnum">${q.id}</span><div class="qprompt">${q.label}</div>${flagButton(q.id)}</div><div class="answer-line"><select data-id="${q.id}"><option value="">— Chọn đáp án —</option>${Object.entries(opts).map(([l,t])=>`<option value="${l}" ${answers[q.id]===l?'selected':''}>${l} — ${t}</option>`).join('')}</select></div></div>`}
function renderSection3(q){const mc=q.filter(x=>x.id<=25),match=q.filter(x=>x.id>=26);return `<div class="instruction"><b>Questions 21–25:</b> Choose the correct letter A, B or C.</div>${mc.map(x=>questionRadio(x,OPTIONS['q'+x.id])).join('')}<div class="instruction"><b>Questions 26–30:</b> Choose FIVE answers from A–G.</div><div class="decision-key">${Object.entries(OPTIONS.decisions).map(([l,t])=>`<div class="key-row"><b>${l}</b><span>${t}</span></div>`).join('')}</div>${match.map(x=>questionSelect(x,OPTIONS.decisions)).join('')}`}
function questionRadio(q,opts){return `<div class="question-card" id="q${q.id}"><div class="qrow"><span class="qnum">${q.id}</span><div class="qprompt">${q.label}</div>${flagButton(q.id)}</div><div class="option-list answer-line">${Object.entries(opts).map(([l,t])=>`<label class="option"><input type="radio" name="q${q.id}" data-id="${q.id}" value="${l}" ${answers[q.id]===l?'checked':''}><span class="letter">${l}</span><span>${t}</span></label>`).join('')}</div></div>`}
function renderSection4(q){const by=id=>q.find(x=>x.id===id),inp=id=>`<span class="inline-num">${id}</span>${inputText(by(id),'one word')}`;return `<div class="instruction"><b>Complete the notes below.</b><br>Write <b>ONE WORD ONLY</b> for each answer.</div><div class="note-sheet"><h2>Marine renewable energy (ocean energy)</h2><h3>Introduction</h3><div class="note-line">More energy required because of growth in population and ${inp(31)}</div><div class="note-line">What’s needed: renewable energy sources; methods that won’t create pollution.</div><h3>Wave energy</h3><div class="note-line">Advantage: waves provide a ${inp(32)} source of renewable energy.</div><div class="note-line">Problems: waves can move in any ${inp(33)}</div><div class="note-line">Movement of sand, etc. on the ${inp(34)} of the ocean may be affected.</div><h3>Tidal energy</h3><div class="note-line">Tides are more ${inp(35)} than waves.</div><div class="note-line">Planned tidal lagoon will be created in a ${inp(36)} at Swansea.</div><div class="note-line">Stored water is released through ${inp(37)}, driving turbines in reverse.</div><div class="note-line">No ${inp(38)} is required to make it work.</div><div class="note-line">Likely to create a number of ${inp(39)}.</div><div class="note-line">May harm fish and birds by affecting ${inp(40)} and building up silt.</div><h3>Ocean thermal energy conversion</h3><div class="note-line">Uses a temperature difference between surface and lower levels.</div></div>`}
function bindInputs(){$$('[data-id]').forEach(el=>{el.oninput=()=>{answers[+el.dataset.id]=el.value;onAnswer(+el.dataset.id)}});$$('[data-flag]').forEach(b=>b.onclick=()=>toggleFlag(+b.dataset.flag));$$('[data-pair]').forEach(cb=>cb.onchange=()=>pairChanged(cb));const obs=new IntersectionObserver(entries=>{const best=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(best){const id=+(best.target.id||'').replace('q','');if(id){currentQuestion=id;updatePalette()}}},{rootMargin:'-190px 0px -55% 0px',threshold:[.1,.5]});$$('.question-card,[id^="q11"],[id^="q13"]').forEach(x=>obs.observe(x));}
function pairChanged(cb){const group=cb.dataset.pair,ids=cb.dataset.ids.split(',').map(Number),checked=$$(`[data-pair="${group}"]:checked`);if(checked.length>2){cb.checked=false;toast('Chỉ được chọn 2 đáp án.');return}ids.forEach((id,i)=>answers[id]=checked[i]?.value||'');ids.forEach(onAnswer);}
function onAnswer(id){currentQuestion=id;updateProgress();updatePalette();scheduleSave()}
function isAnswered(id){return answers[id]!=null&&String(answers[id]).trim()!==''}
function updateProgress(){const done=questions.filter(q=>isAnswered(q.id)).length;$('#answeredLabel').textContent=`${done}/40 đã trả lời`;$('#progressFill').style.width=(done/40*100)+'%'}
function toggleFlag(id){flags[id]=!flags[id];updatePalette();const b=document.querySelector(`[data-flag="${id}"]`);if(b){b.classList.toggle('on',flags[id]);b.textContent=flags[id]?'★':'☆'}persist()}
function goQuestion(id){const q=questions.find(x=>x.id===id);if(q.section!==currentSection)updateSection(q.section,false);currentQuestion=id;setTimeout(()=>{const targetId=id===12?11:id===14?13:id;const el=$('#q'+targetId)||document.querySelector(`[data-id="${id}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'});updatePalette()},50)}
function toggleAudio(){if(mode==='exam'&&examAudioUsed[currentSection]&&(audio.ended||audio.currentTime===0)){toast('Section này đã được phát một lần trong chế độ thi thật.');return}if(audio.paused){if(mode==='exam')examAudioUsed[currentSection]=true;audio.play().catch(()=>toast('Trình duyệt chặn phát audio. Hãy bấm Play lần nữa.'))}else audio.pause()}
function pauseAudio(){if(!audio.paused)audio.pause()}
function updateAudioUI(){const d=audio.duration||0,c=audio.currentTime||0;$('#currentTime').textContent=fmt(c);$('#duration').textContent=fmt(d);$('#seek').value=d?Math.round(c/d*1000):0}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function normalize(v){return String(v??'').toLowerCase().trim().replace(/[.,]/g,'').replace(/£/g,'').replace(/\s+/g,' ')}
function compact(v){return normalize(v).replace(/[\s\-\/]/g,'')}
function gradeOne(q){const user=answers[q.id]||'';if(q.type==='pair'){const selected=[answers[q.group==='advice'?11:13],answers[q.group==='advice'?12:14]].filter(Boolean);return q.answer.includes(String(user).toUpperCase())&&new Set(selected).size===selected.length}return q.answer.some(a=>normalize(user)===normalize(a)||compact(user)===compact(a))}
function submitTest(auto=false){if(results){openResult();return}const blank=questions.filter(q=>!isAnswered(q.id)).length;if(blank&&!auto&&!confirm(`Bạn còn ${blank} câu chưa trả lời. Vẫn nộp bài?`))return;pauseAudio();clearInterval(timerId);const graded=questions.map(q=>({...q,user:answers[q.id]||'',correct:gradeOne(q)}));const score=graded.filter(x=>x.correct).length;results={graded,score,band:bandFrom(score),at:new Date().toISOString()};saveHistory();renderResult();openResult();persist()}
function bandFrom(s){if(s>=39)return 9;if(s>=37)return 8.5;if(s>=35)return 8;if(s>=32)return 7.5;if(s>=30)return 7;if(s>=26)return 6.5;if(s>=23)return 6;if(s>=18)return 5.5;if(s>=16)return 5;if(s>=13)return 4.5;if(s>=11)return 4;if(s>=8)return 3.5;if(s>=6)return 3;return 2.5}
function renderResult(){const {score,band,graded}=results;$('#bandScore').textContent=band.toFixed(1);document.querySelector('.band-ring').style.background=`radial-gradient(circle at center,#fff 54%,transparent 55%),conic-gradient(var(--cyan) 0 ${Math.round(band/9*100)}%,#e5ebf2 ${Math.round(band/9*100)}%)`;$('#resultTitle').textContent=score>=32?'Năng lực nghe rất tốt!':score>=23?'Nền tảng khá — cần sửa đúng nhóm lỗi.':'Đã xác định được điểm yếu trọng tâm.';$('#resultSummary').textContent=`Bạn đúng ${score}/40 câu. Band ${band.toFixed(1)} là mức quy đổi ước tính phổ biến; điểm chính thức có thể thay đổi nhẹ theo từng đề.`;$('#wrongCount').textContent=40-score;$('#sectionStats').innerHTML=[1,2,3,4].map(s=>{const a=graded.filter(x=>x.section===s),n=a.filter(x=>x.correct).length;$('#secScore'+s).textContent=`${n}/10`;return `<div class="stat-card"><small>SECTION ${s}</small><b>${n}/10</b><span>${SECTION_META[s].title}</span></div>`}).join('');const skills={};graded.filter(x=>!x.correct).forEach(x=>skills[x.skill]=(skills[x.skill]||0)+1);const sorted=Object.entries(skills).sort((a,b)=>b[1]-a[1]);const top=sorted[0];$('#diagnosisTitle').textContent=top?`Lỗi nổi bật: ${top[0]}`:'Không có nhóm lỗi nổi bật';$('#diagnosisText').textContent=top?`Bạn sai ${top[1]} câu thuộc nhóm ${top[0]}. Hãy mở phần chữa chi tiết, nghe lại đúng đoạn chứa từ khóa và ghi lại cách đề paraphrase.`:'Bạn đã xử lý rất tốt các dạng câu hỏi trong bài.';$('#skillBars').innerHTML=(sorted.length?sorted.slice(0,5):[['Accuracy',0]]).map(([k,v])=>`<div class="skill-bar"><span>${k}</span><div class="skill-track"><i style="width:${Math.min(100,v/Math.max(1,40-score)*100)}%"></i></div><b>${v}</b></div>`).join('')}
function openResult(){$('#resultModal').classList.remove('hidden')}
function openReview(wrong=false){if(!results)return;$('#resultModal').classList.add('hidden');$('#wrongOnly').checked=wrong;renderReview();$('#reviewModal').classList.remove('hidden')}
function renderReview(){if(!results)return;const wrongOnly=$('#wrongOnly').checked;const arr=results.graded.filter(x=>!wrongOnly||!x.correct);$('#reviewList').innerHTML=arr.length?arr.map(x=>`<section class="review-item ${x.correct?'correct':'wrong'}"><div class="review-main"><span class="review-status">${x.correct?'✓':'×'}</span><div><h4>Question ${x.id} — ${esc(x.label)}</h4><div class="answer-compare"><span class="answer-chip ${x.correct?'good':'bad'}">Bạn chọn: ${esc(x.user||'—')}</span><span class="answer-chip good">Đáp án: ${esc(displayAnswer(x))}</span></div></div><span class="skill-tag">${esc(x.skill)}</span></div><div class="review-explain"><b>Vì sao:</b> ${esc(x.explain)}<div class="cue"><b>Dấu hiệu nghe:</b> “${esc(x.cue)}”</div>${x.trap?`<div><b>Bẫy:</b> ${esc(x.trap)}</div>`:''}</div></section>`).join(''):'<div class="instruction">Tuyệt vời — không có câu sai trong bộ lọc này.</div>'}
function displayAnswer(q){if(q.type==='pair')return q.answer.join(' / ')+' (any order)';return q.answer[0]}
function resetTest(skipConfirm=false){if(!skipConfirm&&!confirm('Xóa toàn bộ câu trả lời và làm lại từ đầu?'))return;answers={};flags={};results=null;timeLeft=2400;examAudioUsed={};localStorage.removeItem('ielts-progress-v1');closeAll();renderPaper();updateProgress();updatePalette();$$('[id^="secScore"]').forEach(x=>x.textContent='');$('#wrongCount').textContent='0';if(mode==='exam')startTimer();toast('Đã tạo lượt làm bài mới.')}
function closeAll(){$$('.modal').forEach(x=>x.classList.add('hidden'))}
function scheduleSave(){clearTimeout(saveTimer);$('#saveState').textContent='● Đang lưu';saveTimer=setTimeout(()=>{persist();$('#saveState').textContent='● Đã lưu'},450)}
function persist(){localStorage.setItem('ielts-progress-v1',JSON.stringify({answers,flags,currentSection,timeLeft,mode,examAudioUsed,results}))}
function restore(){try{const s=JSON.parse(localStorage.getItem('ielts-progress-v1'));if(s){answers=s.answers||{};flags=s.flags||{};timeLeft=s.timeLeft??2400;examAudioUsed=s.examAudioUsed||{};results=s.results||null}}catch(e){}const n=localStorage.getItem('ielts-name');if(n)$('#candidateName').value=n}
function saveHistory(){const h=JSON.parse(localStorage.getItem('ielts-history-v1')||'[]');h.unshift({score:results.score,band:results.band,at:results.at});localStorage.setItem('ielts-history-v1',JSON.stringify(h.slice(0,10)))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._id);t._id=setTimeout(()=>t.classList.remove('show'),2400)}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
init().catch(e=>{document.body.innerHTML=`<div style="padding:30px;font-family:Arial"><h2>Không thể khởi động ứng dụng</h2><p>${esc(e.message)}</p><p>Hãy giải nén toàn bộ thư mục rồi mở lại index.html.</p></div>`});
